
update tblVideo set content = 'https://www.youtube.com/embed/WLU26nqcvfY' where  videoID = 1
update tblVideo set content = 'https://www.youtube.com/embed/iwRa5qTnr8o' where  videoID = 2
update tblVideo set content = 'https://www.youtube.com/embed/xTFmwj5kch8' where  videoID = 3
update tblVideo set content = 'https://www.youtube.com/embed/BgjxHJp_XYc' where  videoID = 4
update tblVideo set content = 'https://www.youtube.com/embed/ZPdJAKIR-Bs' where  videoID = 5
update tblVideo set content = 'https://www.youtube.com/embed/GMTvqj7gDOA' where  videoID = 6
update tblVideo set content = 'https://www.youtube.com/embed/EjorOn7jAs' where  videoID = 7
update tblVideo set content = 'https://www.youtube.com/embed/0RmGV5wALG0' where  videoID = 8
update tblVideo set content = 'https://www.youtube.com/embed/iyfr5D_7gxc' where  videoID = 9
update tblVideo set content = 'https://www.youtube.com/embed/eXcKOqviLE0' where  videoID = 10
update tblVideo set content = 'https://www.youtube.com/embed/Mvf_wvzMW9w' where  videoID = 11
update tblVideo set content = 'https://www.youtube.com/embed/7FngQ0WPe_c' where  videoID = 12
update tblVideo set content = 'https://www.youtube.com/embed/fJvcllrOrr4' where  videoID = 13
update tblVideo set content = 'https://www.youtube.com/embed/SQ06N4q-zpk' where  videoID = 14
update tblVideo set content = 'https://www.youtube.com/embed/r6HaTRvcMiU' where  videoID = 15
update tblVideo set content = 'https://www.youtube.com/embed/BDePyEFT1gQ' where  videoID = 16
update tblVideo set content = 'https://www.youtube.com/embed/bJzGkZwkHt4' where  videoID = 17
update tblVideo set content = 'https://www.youtube.com/embed/9DIPs3T2dQk' where  videoID = 18
update tblVideo set content = 'https://www.youtube.com/embed/AAwYHNo31ZQ' where  videoID = 19
update tblVideo set content = 'https://www.youtube.com/embed/U11B_0FCn6o' where  videoID = 20
update tblVideo set content = 'https://www.youtube.com/embed/STsC8tdbSEk' where  videoID = 21
update tblVideo set content = 'https://www.youtube.com/embed/dm9XcTCKpUw' where  videoID = 22
update tblVideo set content = 'https://www.youtube.com/embed/uRHCZTw_vjs' where  videoID = 23
update tblVideo set content = 'https://www.youtube.com/embed/AQiYbpGZadU' where  videoID = 24
update tblVideo set content = 'https://www.youtube.com/embed/thZlNmTbgPs' where  videoID = 25
update tblVideo set content = 'https://www.youtube.com/embed/AEJ3yWp1uUE' where  videoID = 26
update tblVideo set content = 'https://www.youtube.com/embed/PE86v4BBT3w' where  videoID = 27
update tblVideo set content = 'https://www.youtube.com/embed/2EH95eox9VE' where  videoID = 28
update tblVideo set content = 'https://www.youtube.com/embed/B6zFJKCDQqU' where  videoID = 29
update tblVideo set content = 'https://www.youtube.com/embed/ZRaKqe-LP2Q' where  videoID = 30
update tblVideo set content = 'https://www.youtube.com/embed/W-FB-iX7T68' where  videoID = 31
update tblVideo set content = 'https://www.youtube.com/embed/YeGALdJPchM' where  videoID = 32
update tblVideo set content = 'https://www.youtube.com/embed/ymNcm4Ep4sA' where  videoID = 33
update tblVideo set content = 'https://www.youtube.com/embed/X30jkF7Kmdo' where  videoID = 34
update tblVideo set content = 'https://www.youtube.com/embed/PGcOEkl1coU' where  videoID = 35
update tblVideo set content = 'https://www.youtube.com/embed/EAQTeyWlXyQ' where  videoID = 36
update tblVideo set content = 'https://www.youtube.com/embed/yS6R2l8t8wo' where  videoID = 37
update tblVideo set content = 'https://www.youtube.com/embed/eAhHgPZASYQ' where  videoID = 38
update tblVideo set content = 'https://www.youtube.com/embed/eabPsiWaimE' where  videoID = 39
update tblVideo set content = 'https://www.youtube.com/embed/2CmrMRXoA8Q' where  videoID = 40
update tblVideo set content = 'https://www.youtube.com/embed/ycFHNTACIrk' where  videoID = 41
update tblVideo set content = 'https://www.youtube.com/embed/9m4Hf_6U4Rc' where  videoID = 42
update tblVideo set content = 'https://www.youtube.com/embed/aPflB7_XXaY' where  videoID = 43
update tblVideo set content = 'https://www.youtube.com/embed/tIAeexfkssw' where  videoID = 44
update tblVideo set content = 'https://www.youtube.com/embed/E1RiMecwZlA' where  videoID = 45
update tblVideo set content = 'https://www.youtube.com/embed/jS7ib3-ET5M' where  videoID = 46
update tblVideo set content = 'https://www.youtube.com/embed/UdMTZE7DDMM' where  videoID = 47
update tblVideo set content = 'https://www.youtube.com/embed/1Bi8wqbpCSQ' where  videoID = 48
update tblVideo set content = 'https://www.youtube.com/embed/mysAqNK6CHI' where  videoID = 49
update tblVideo set content = 'https://www.youtube.com/embed/vgfdrf1BsJY' where  videoID = 50
update tblVideo set content = 'https://www.youtube.com/embed/kn_4I6x0Y3I' where  videoID = 51
update tblVideo set content = 'https://www.youtube.com/embed/RnKo1UtF9PM' where  videoID = 52
update tblVideo set content = 'https://www.youtube.com/embed/lb1WrQp2EAI' where  videoID = 53
update tblVideo set content = 'https://www.youtube.com/embed/N0vWyKyYv4o' where  videoID = 54
update tblVideo set content = 'https://www.youtube.com/embed/GmTya4Z6UTQ' where  videoID = 55
update tblVideo set content = 'https://www.youtube.com/embed/wYtsLhMDFYs' where  videoID = 56
update tblVideo set content = 'https://www.youtube.com/embed/aM1EJn1zEFA' where  videoID = 57
update tblVideo set content = 'https://www.youtube.com/embed/efHmX_mp3Ts' where  videoID = 58
update tblVideo set content = 'https://www.youtube.com/embed/nIoXOplUvAw' where  videoID = 59
update tblVideo set content = 'https://www.youtube.com/embed/bxelGdpMx-w' where  videoID = 60
update tblVideo set content = 'https://www.youtube.com/embed/QuVZGDbly3g' where  videoID = 61
update tblVideo set content = 'https://www.youtube.com/embed/2WSguIVrrKI' where  videoID = 62
update tblVideo set content = 'https://www.youtube.com/embed/o0uc4sRArjE' where  videoID = 63
update tblVideo set content = 'https://www.youtube.com/embed/yxGb3hVGPyk' where  videoID = 64
update tblVideo set content = 'https://www.youtube.com/embed/s7NFsEPBtcA' where  videoID = 65
update tblVideo set content = 'https://www.youtube.com/embed/6xcUQNwDRps' where  videoID = 66
update tblVideo set content = 'https://www.youtube.com/embed/SD62YJ6u9KM' where  videoID = 67
update tblVideo set content = 'https://www.youtube.com/embed/hQEW164vILA' where  videoID = 68
update tblVideo set content = 'https://www.youtube.com/embed/46fIGJ75z-k' where  videoID = 69
update tblVideo set content = 'https://www.youtube.com/embed/-37sv5hhwOQ' where  videoID = 70
update tblVideo set content = 'https://www.youtube.com/embed/vKKqxN7VfpI' where  videoID = 71
update tblVideo set content = 'https://www.youtube.com/embed/kMDB7c0ZiKA' where  videoID = 72
update tblVideo set content = 'https://www.youtube.com/embed/AB8MpLHVpHY' where  videoID = 73
update tblVideo set content = 'https://www.youtube.com/embed/7JUNlj6mR0U' where  videoID = 74
update tblVideo set content = 'https://www.youtube.com/embed/pCFD80MHQ0A' where  videoID = 75
update tblVideo set content = 'https://www.youtube.com/embed/rjbN-z7MSWk' where  videoID = 76
update tblVideo set content = 'https://www.youtube.com/embed/FkaVtOkLJoI&t=91s' where  videoID = 77
update tblVideo set content = 'https://www.youtube.com/embed/nGP65blafjo' where  videoID = 78
update tblVideo set content = 'https://www.youtube.com/embed/IAiTYaiZmY0' where  videoID = 79
update tblVideo set content = 'https://www.youtube.com/embed/iiZbeJ_ep2k' where  videoID = 80
update tblVideo set content = 'https://www.youtube.com/embed/SXQLqhe1Ag0' where  videoID = 81
update tblVideo set content = 'https://www.youtube.com/embed/u43Fsl-FTcA' where  videoID = 82
update tblVideo set content = 'https://www.youtube.com/embed/TumrA0XsX0A' where  videoID = 83
update tblVideo set content = 'https://www.youtube.com/embed/R1tv1mgiOkQ' where  videoID = 84
update tblVideo set content = 'https://www.youtube.com/embed/Ze7DCP7Hxzo' where  videoID = 85
update tblVideo set content = 'https://www.youtube.com/embed/gyLSZIbXI0g' where  videoID = 86
update tblVideo set content = 'https://www.youtube.com/embed/ilt0enQ24_8' where  videoID = 87
update tblVideo set content = 'https://www.youtube.com/embed/DK5KaVyyHt4' where  videoID = 88
update tblVideo set content = 'https://www.youtube.com/embed/6PcRn0_ewU0' where  videoID = 89
update tblVideo set content = 'https://www.youtube.com/embed/WlHwB7kcieQ' where  videoID = 90
update tblVideo set content = 'https://www.youtube.com/embed/T3RApx4-1iA' where  videoID = 91
update tblVideo set content = 'https://www.youtube.com/embed/eFHxknDs4Mk' where  videoID = 92
update tblVideo set content = 'https://www.youtube.com/embed/Uzig2s7pNss' where  videoID = 93
update tblVideo set content = 'https://www.youtube.com/embed/tSWu817nZjs' where  videoID = 94
update tblVideo set content = 'https://www.youtube.com/embed/EvnaJDvgEmM' where  videoID = 95
update tblVideo set content = 'https://www.youtube.com/embed/0tSVG0tEbPQ' where  videoID = 96
update tblVideo set content = 'https://www.youtube.com/embed/Ocaa2k9m5c' where  videoID = 97
update tblVideo set content = 'https://www.youtube.com/embed/Ka6rKayjiNM' where  videoID = 98
update tblVideo set content = 'https://www.youtube.com/embed/9a8uegEWWHU' where  videoID = 99
update tblVideo set content = 'https://www.youtube.com/embed/2TbzxWploGI' where  videoID = 100
update tblVideo set content = 'https://www.youtube.com/embed/3BI5UUMiMD8' where  videoID = 101
update tblVideo set content = 'https://www.youtube.com/embed/23udufdFaQ0' where  videoID = 102
update tblVideo set content = 'https://www.youtube.com/embed/1GoZC30hq50' where  videoID = 103
update tblVideo set content = 'https://www.youtube.com/embed/ZgKmr2HF1WQ' where  videoID = 104


